FROM docker.io/matejc/rf-novnc:SeleniumLibrary

USER pwuser

ADD ./requirements-SeleniumLibrary.txt /home/pwuser/requirements.txt
RUN python3 -m pip install --user -r /home/pwuser/requirements.txt

USER root
